name: Security Scan

on: [pull_request]

permissions:
  pull-requests: write
  statuses: write

jobs:
  scan:
    uses: PRACHIT27/SecureGateway/.github/workflows/reusable-scan.yml@main
    with:
      ecr-repo: 772312904084.dkr.ecr.us-east-1.amazonaws.com
      s3-bucket: securegateway-reports-772312904084
    secrets:
      api-gateway-url: ${{ secrets.SECUREGATEWAY_API_URL }}
      api-key: ${{ secrets.SECUREGATEWAY_API_KEY }}
      aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
